### ISSUE TITLE
OmniAuth link appears broken

### ISSUE THREAD

**Issue by jmoglesby** [chessplayers/chess#10]
Pull Request #8 added OmniAuth through Google. I pulled down the most recent code, ran `$ bundle install`, booted up the server, and clicked the "Sign in With Google" link:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/25443574/67450714-28a02800-f5d3-11e9-8114-82fadf2ecd04.png">

:( bummer

**Comment by jmoglesby** [comment]
I notice that in the URL (in my screenshot) there is a `&client_id` parameter present, but it is not set to anything... ie, there's no `=VALUE` following it.

**Comment by seansinger22** [comment]
You are missing my application.yml file.  I sent the  file to you in slack.  Add that to your local project and let me know if that fixes the problem.  At the moment the client_id and the client_secret are missing from your local project.

**Comment by jmoglesby** [comment]
<img width="798" alt="Screen Shot 2019-10-23 at 10 03 21 PM" src="https://user-images.githubusercontent.com/25443574/67455083-46748980-f5e1-11e9-82c7-f2e4c4bee373.png">

There's a `client_id` now, but that gives a new error. I'm not sure I understand what this error is getting at, but it seems it's directing you to your personal google/api's dashboard.

**Comment by seansinger22** [comment]
why is your localhost set to 3000?  it should be set to 3030.  That is the URI I have authorized.  Did you change your localhost?  I added the 3000 URI to the allowed callbacks.  Give it a few minutes and let me know if it still doesn't work.  You are very close now.

**Comment by jmoglesby** [comment]
I'm running the project in my local environment, not `vagrant`... when you just run `$ rails s` from your local environment, the server defaults to port:3000... sorry

**Comment by seansinger22** [comment]
No problem.  It should work now, I added that 3000 callback to allowed callbacks.  They say it can take up to 10 minutes, but it started working for me after a couple minutes.  Let me know if it still doesn’t work.

Sean
